### ISSUE TITLE
[Crash] Windows 8.1 Pro

### ISSUE THREAD

**Issue by lavanoid** [Rinnegatamante/lpp-3ds#1]
Hi,

Tried running "vid2bmov" but I get the following error message: "The application was unable to start coorectly (0xc000007b). Click OK to close the application."

I'm using a 64BIT system too.

As for BMPV Creator (the GUI version), that sort of works. When I try and convert the file though, I get the following error: "Unhandled exception has occurred in your aplication... Could not find file '.\temp\audio.wav'.

Here are the details:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.FileNotFoundException: Could not find file '.\temp\audio.wav'.
File name: '.\temp\audio.wav'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at BMPV_Creator.Form1.Button2_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
BMPV Creator
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Lavanoid/Documents/3DS/BMPV_Creator_BETA_RELEASE_2/BMPV%20Creator.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8009 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8008 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8007 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.8012 (FX35W81RTMGDR.050727-8000)
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Rinnegatamante** [comment]
Have you properly edited batch script in vid2bmpv release? (Also keep in mind that you have to use Batch script and not vid2bmpv executable directly).

For BMPV Creator you need to install Microsoft .NET Framework 3.5.

**Comment by lavanoid** [comment]
Yeah, I've tried everything. I also have Micosoft .NET Framework 3.5, as you described - installed.

I had to replace ffmpeg with a different version - it worked without problems after converting but when bmpv_encoder.exe is executed - I get the same message. I'm positive that I followed all of the instructions correctly.

**Comment by lavanoid** [comment]
I did use the batch script too (after modifying it of course)

**Comment by Rinnegatamante** [comment]
Try to give administration privileges to bmpv_encoder.

P.s. What CPU did you have?

**Comment by lavanoid** [comment]
I'm using a 64bit Intel Core i3 @ 1.7Ghz - Dual core, 4 logical cores.

I haven't ran it with Admin perms yet, but I doubt that's the issue, its a file converter afterall.

**Comment by Rinnegatamante** [comment]
It needs read/writing permission on temp and input file folder.

**Comment by lavanoid** [comment]
Still doesn't work...

**Comment by Rinnegatamante** [comment]
I read on tomshardware that is a common issue of Windows 8.1. Try to:

1) Set Windows 7 Compatibility Mode for all executables (ffmpeg, bmpv_encoder)
2) Install Microsoft Visual C++

If it doesn't work, i think you have to sets up a Virtual Machine with Windows XP/Vista/7 :/

**Comment by lavanoid** [comment]
HHHmm. I'll give it a shot and I'll let you know.
