### ISSUE TITLE
Trying to create CIA

### ISSUE THREAD

**Issue by amspady20** [Rinnegatamante/lpp-3ds#13]
When trying to use the "makerom" tool, the "rsf" file shows that there is an unrecoginized key.

C:\Users\Alex\Git-Stuff\Project_CTR\makerom>makerom -f cia -rsf C:\Users\Alex\Downloads\lpp-3ds_r4\Workarounds\cia_workaround.rsf -target t
[RSF ERROR] Unrecognised Key: 'ExeFs'
[RSF ERROR] Error Proccessing RSF file

Thanks for any help.  Have a good one.

**Comment by Rinnegatamante** [comment]
Probably it's caused by a newer version of makerom. Are you using the one provided in the repository?

**Comment by amspady20** [comment]
@Rinnegatamante No.  That's probably it.  Thanks for the speedy reply.

**Comment by amspady20** [comment]
@Rinnegatamante It worked.  Thanks much.
