### ISSUE TITLE
Copying to Clipboard?

### ISSUE THREAD

**Issue by The-Sparrow** [Rinnegatamante/lpp-3ds#20]
Is there any way to set a line of text to copy to the 3DS clipboard?
I'd love to do this but im not sure how..

**Comment by ihaveamac** [comment]
the 3DS doesn't have a clipboard, does it? you can just store a value in a variable...

**Comment by The-Sparrow** [comment]
The web browser does. And i think the clipboard is also used in Miiverse too.

**Comment by ihaveamac** [comment]
but that's not a system-wide clipboard.

**Comment by The-Sparrow** [comment]
Okay! Thanks for the quick reply!
