### ISSUE TITLE
Depreciated pixel format used

### ISSUE THREAD

**Issue by Boured** [Rinnegatamante/lpp-3ds#21]
Hello I have a problem which is probably something that is so easy to fix that it will make me look like a idiot ^^

Basically what happens is when I try to put the frame size and I set the resolution to 400x240, which is the resolution for the 3ds/2ds screen. Though when I put it the file it and do the rest of the things it want's me to do it says.

"Depreciated pixel format used, make sure you did set the right one" or something to that nature.

Pretty sure I'm just being stupid, but any help is appreciated.

**Comment by The-Sparrow** [comment]
What format is your image in?

**Comment by Boured** [comment]
.mp4, does it need to be in a different format for it to work?

**Comment by Rinnegatamante** [comment]
I'm assuming you're refering to vid2jpgv. Anyway, it's not an error but a warning, just ignore it.

Also remember to use height x width when inserting your resolution (so 240x400).

**Comment by Boured** [comment]
Got ya, thanks a lot ^^
