### ISSUE TITLE
System.launch3DSX Freezes While launching

### ISSUE THREAD

**Issue by DarkPanda66** [Rinnegatamante/lpp-3ds#23]
Whenever i try to launch a .3DSX via lpp-3ds, it freezes the app, and doesent do anything past that point.

**Comment by Rinnegatamante** [comment]
Are you using R5 or nightly build?

**Comment by DarkPanda66** [comment]
I tried with both R5 and the nightly build

**Comment by Rinnegatamante** [comment]
Nightly build shouldn't have these problems. Does the 3dsx you're trying to launch have an XML descriptor?

**Comment by DarkPanda66** [comment]
No, i can try again with the nightly when i get home from work, i think i may have found my problem.

**Comment by DarkPanda66** [comment]
Just upgraded from R3 Safe to R5 nightly, and what i made isn't even showing up anymore. What changed that could've made my code not even show up?

**Comment by Rinnegatamante** [comment]
There are no "r5" nightly. Anyway, without seeing the code, i can't tell yu where you're wrong.

**Comment by DarkPanda66** [comment]
Is the unsafe build not a nightly?
If you could link to it i would highly appreciate it

**Comment by Rinnegatamante** [comment]
http://rinnegatamante.it/lpp-3ds.php

**Comment by DarkPanda66** [comment]
Alright thanks, i think i can get this to work now.
