### ISSUE TITLE
Sample cia_installer issue.

### ISSUE THREAD

**Issue by mariohackandglitch** [Rinnegatamante/lpp-3ds#25]
Core.execCall("AM_FinishCiaInstall", 0x01, cia_handle) returns Error: [string "?"]: unknown syscall

(Using lastest build)

**Comment by Rinnegatamante** [comment]
Replace it with Core.execCall("AM_FinishCiaInstall", cia_handle) and it should work (just a recent change in ctrulib syntax).

**Comment by mariohackandglitch** [comment]
Did that, however it now doesn't install.

**Comment by Rinnegatamante** [comment]
Are you using it on a CFW with CIA version?
If not, you must have signpatch enabled to install non legit CIAs or you must use the USE_MEMCHUNKHAX2 flag for fw >= 9.3.

**Comment by mariohackandglitch** [comment]
As I already said, it is a cia build, in Luma3DS a9lh.

**Comment by Rinnegatamante** [comment]
Already said where? O.o

Anyway if the installation fails, one of the execCall calls should return an error.
