### ISSUE TITLE
Network.downloadFile freezes program

### ISSUE THREAD

**Issue by SpooneyH20** [Rinnegatamante/lpp-3ds#27]
When downloading a file via HTTP it freezes the program, and doesent download the file.

Code im using: 

`if (Controls.check(pad,KEY_A) ) then
   Network.downloadFile("http://example.com/example.zip","Example.zip"`

Is there any way to download a file without it freezing the entire program?

**Comment by Rinnegatamante** [comment]
You must write a proper download function using sockets. If you have C knowledge, you can take a look at TSOI PC downloader sourcecode and try to port it to lpp-3ds for example: https://github.com/Rinnegatamante/The-Sharing-Of-Isaac/blob/master/PC/downloader/downloader.cpp

**Comment by SpooneyH20** [comment]
I can try my best, but im confused on whether this was ever a working function?

**Comment by Rinnegatamante** [comment]
What are you talking about? If you refer to TSOI code, yes it works perfectly.

**Comment by SpooneyH20** [comment]
Im talking about was this ever a working function? As of now you cannot download a file via HTTP, was this ever working? Or has it been broken, and can be classified as a bug?

**Comment by Rinnegatamante** [comment]
Network.downloadFile works fine. IT's used on several homebrews like CHMM2 for example.

**Comment by SpooneyH20** [comment]
You're making little to no sense. 
First you saying i have to port TSOI PC downloader to properly open a socket/use Network.downloadFile.
Now your telling me it works fine? Is something wrong with my code, or is something wrong with the lpp-3ds build?

**Comment by Rinnegatamante** [comment]
Socket != downloadFile. downloadFile uses httpc:C service. Socketing uses soc:U service.

In lpp-3ds they also refer to different modules.

**Comment by SpooneyH20** [comment]
My mistake, thanks for this.
