### ISSUE TITLE
System.launch3DSX causes error

### ISSUE THREAD

**Issue by Pirater12** [Rinnegatamante/lpp-3ds#28]
Whenever i try to load a 3dsx with .cia version of lpp-3ds it will exit to the homemenu and display the error;-"An error has occured,forcing the software to close.The system will now restart."
I am on 10.7 reinand.Please help

Also the 3dsx does not have an xml file

**Comment by Rinnegatamante** [comment]
CIA/3DS version of lpp-3ds can't launch 3DSX files obviously.
