### ISSUE TITLE
How to change directory for script to load from.

### ISSUE THREAD

**Issue by nickthegamer5** [Rinnegatamante/lpp-3ds#29]
I'm working on a project in luaPP and I'm trying to make a CIA out of it, but I want to know how I can put it into a folder like this
PayloadUpdater/script.lua
but how would I do it?

**Comment by Rinnegatamante** [comment]
You can change it by editing this and rebuilding the source: https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/main.cpp#L139
