### ISSUE TITLE
Launch installed cia/title?

### ISSUE THREAD

**Issue by lukas2511** [Rinnegatamante/lpp-3ds#3]
Hey,

I'm trying to use your lua stuff to build a simple tool that installs a cia from network and launches it (a bit like the netloader thing i build for 3ds_hb_menu, but just over http because i don't want to touch sockets again...)

So far i got it to download the cia, install it, and exit back to homescreen where I can then launch my app, but I wonder if you could implement something to launch a specified title directly (it seems to be possible, at least DevMenu can do it)

**Comment by Rinnegatamante** [comment]
I'm working on this feature both for lpp-3ds and Big Red Menu.

**Comment by lukas2511** [comment]
Great! I have done some experiments but was only able to launch system titles, on homebrew it crashed every single time :( Hoping for this feature in the near future :)

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/lpp-3ds/commit/b3979e3ad4465bddd2c8d51f7916017606486250
