### ISSUE TITLE
Sockets not working.

### ISSUE THREAD

**Issue by mariohackandglitch** [Rinnegatamante/lpp-3ds#30]
Tried to request a http file with sockets.
function testsocket()
    Socket.init()
    checksckt = Socket.connect("ctgp.dshack.org", 80, false) -- (Also tried with the ip 133.130.123.204, still doesn't work)
    Socket.send(checksckt, "GET /check.txt HTTP/1.0\r\n\r\n")
    checkscktdata = Socket.receive(checksckt, 1024)
    Socket.term()
end
Printing checkscktdata returns: " " (nothing)

**Comment by Rinnegatamante** [comment]
You don't even wait between sent data and receive function. It's normal that your code results in an empty string.

**Comment by mariohackandglitch** [comment]
How much should I wait then.

**Comment by Rinnegatamante** [comment]
It depends on server quality, connection quality, etc...

Normally, a loop should be used, for example: https://github.com/Rinnegatamante/CHMM2/blob/master/source/index.lua#L1170-L1228

**Comment by mariohackandglitch** [comment]
Yes, I figured it out, thanks :D. I tried now to connect to an https server, but using ssl returns couldn't stablish ssl connection, and setting it to false crashes.

**Comment by mariohackandglitch** [comment]
function testsocket()
	checksckt = Socket.connect("ctgp.dshack.org", 80)
	Socket.send(checksckt, "GET /check.txt HTTP/1.0\r\nHost: ctgp.dshack.org\r\n\r\n")
	sockettmr = Timer.new()
	globalsockettmr = Timer.new()
	while true do
		Sound.updateStream()
		if (Timer.getTime(sockettmr)>=2000) then
			Timer.reset(sockettmr)
			checkscktdata = Socket.receive(checksckt, 4096)
			if (Timer.getTime(globalsockettmr) >= 5000) then
				Timer.destroy(globalsockettmr)
				checkscktdata = "Timed out!"
			end
			if (string.len(checkscktdata) > 2) then
				Timer.destroy(sockettmr)
				break				
			end
		end
	end
	Console.clear(console)
	Console.append(console, tostring(checkscktdata))
	Socket.close(checksckt)
end

I've tried this, but randomly works, and other times lpp3ds crashes and reboots.

**Comment by mariohackandglitch** [comment]
I created this function:
```
function socket_downloadfile(string_host, number_port, bool_usessl, string_path, number_chunksize, number_checktimeout, string_savepath)
	if (System.doesFileExist(string_savepath)) then
		System.deleteFile(string_savepath)
	end
	checksckt = Socket.connect(string_host, number_port)
	sockettimeout = Timer.new()
	Socket.send(checksckt, "GET "..string_path.." HTTP/1.0\r\nHost: "..string_host.."\r\n\r\n")
	checkscktdata = ""
	while (string.len(checkscktdata) == 0) do
		checkscktdata = Socket.receive(checksckt, number_chunksize)
		if (Timer.getTime(sockettimeout) > number_checktimeout) then
			return "Timed out!"
		end
	end
	_,bytesoffset = string.find(checkscktdata, "Length: ") -- Search for the Content-Length data
	checkscktdata = string.sub(checkscktdata, bytesoffset) -- Ignore everything until Content-Length
	contentsize = tonumber(string.match(checkscktdata, '%d+')) -- Get the value (number of bytes)
	fileStream = io.open(string_savepath,FCREATE)
	_,contentoffset = string.find(checkscktdata, "\r\n\r\n") -- Find the 2 newlines (start of the content)
	checkscktdata = string.sub(checkscktdata, contentoffset + 1) -- Ignore everything but the actual content.
	io.write(fileStream,0,checkscktdata, string.len(checkscktdata)) -- Write first chunk to file.
	numberchunks = 0
	Timer.reset(sockettimeout)
	while (Timer.getTime(sockettimeout) < number_checktimeout) do -- Socket closes after data transfering, so I create this to check when the socket closes.
		scktdata = Socket.receive(checksckt, number_chunksize) -- Receive next chunk of data
		if (string.len(scktdata) > 0) then
			io.write(fileStream, io.size(fileStream), scktdata, number_chunksize) -- Write data to the end of the file.
			numberchunks = numberchunks + 1
			Screen.waitVblankStart()
			Screen.refresh()
			Screen.clear(TOP_SCREEN)
			Font.print(font,0,0,"Downloaded "..io.size(fileStream).." bytes of "..tostring(contentsize).." ( "..((number_chunksize*numberchunks / contentsize) * 100).."% )",Color.new(255,255,255), TOP_SCREEN) -- Print info.
			Screen.flip()
			Timer.reset(sockettimeout)
		end
	end
	Socket.close(checksckt)
	io.close(fileStream)
	return true
end
```

Called it with: 
`socket_downloadfile("www.dshack.org", 80, false, "/assets/store/164/ntr.zip", 10240, 10000, "/file.zip")`

However, the file is 439566 bytes, but is instead downloading 567013 bytes for some reason...

The result file is corrupted, entire chunks of data are missing.
