### ISSUE TITLE
Cannot download a file hosted via https

### ISSUE THREAD

**Issue by MatMaf** [Rinnegatamante/lpp-3ds#32]
Network.downloadFile("https://3ds.titlekeys.com/downloadenc/", "/encTitleKeys.bin")

Downloaded bin comes out as 0 bytes.

Edit: I'm using the latest nightly

**Comment by Rinnegatamante** [comment]
Hostname resolver cannot resolve subdomains actually.

**Comment by MatMaf** [comment]
So what do I have to do? Is this going to be fixed in a following nightly?

**Comment by Rinnegatamante** [comment]
You have to use "direct" link to the resorce (no redirects due to subdomains).

**Comment by MatMaf** [comment]
That is the direct link though AFAIK. It doesn't have an extension.

**Comment by Rinnegatamante** [comment]
http://titlekeys.com/SOMETHING is the direct link, 3ds.titlekeys.com is a subdomain.

**Comment by MatMaf** [comment]
Ahh, I see. Thanks.
