### ISSUE TITLE
SSL socket failing to connect.

### ISSUE THREAD

**Issue by mariohackandglitch** [Rinnegatamante/lpp-3ds#33]
Trying to connect to a https website (Socket.connect(www.dshack.org, 443, true)) fails with: "Error:[string"?"]:56: SSL connection failed."

**Comment by Rinnegatamante** [comment]
Looks like your client doesn't have needed certificates to connect to the server. Does the website use particular certificates?

**Comment by mariohackandglitch** [comment]
You mean Network.addCertificate? (or something like that) How could I make one for my page? I searched on google and nothing.

**Comment by Rinnegatamante** [comment]
Certificates are in der format. I never built one by myself since i never felt the need.

**Comment by mariohackandglitch** [comment]
I used Chrome to get the certificate from dshack.org, still SSL connection failed. (Tried ports 80, 443)

**Comment by ksanislo** [comment]
Just to thrown in my $0.02... it might be best to just disable certificate checking for sockets in general. 
Basically, when you [create your ssl:c context](https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaNetwork.cpp#L580) you can just apply the [same option bit used to disable cert verification for http:c](https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaNetwork.cpp#L150)

**Comment by Rinnegatamante** [comment]
Yep, pushed a modification as @ksanislo suggested. https://github.com/Rinnegatamante/lpp-3ds/commit/47af2ebfa253ab0b2406a41c14cc7fde20d5640e should fix the problem.
