### ISSUE TITLE
Error while try to compile newest commit

### ISSUE THREAD

**Issue by Pirater12** [Rinnegatamante/lpp-3ds#34]
c:/Users/Dell/Desktop/lpp-3ds-master/source/luaSound.cpp: In function 'void stre
amDEC_CSND(void*)':
c:/Users/Dell/Desktop/lpp-3ds-master/source/luaSound.cpp:424:54: error: 'struct
wav' has no member named 'misc'
    AudioDecoder* audio_decoder = (AudioDecoder*)src->misc;
                                                      ^
c:/Users/Dell/Desktop/lpp-3ds-master/source/luaSound.cpp: In function 'int lua_o
penmp3_old(lua_State*)':
c:/Users/Dell/Desktop/lpp-3ds-master/source/luaSound.cpp:677:23: error: 'CSND_EN
CODING_MPEG' was not declared in this scope
  wav_file->encoding = CSND_ENCODING_MPEG;
                       ^
c:/Users/Dell/Desktop/lpp-3ds-master/source/luaSound.cpp:682:12: error: 'struct
wav' has no member named 'misc'
  wav_file->misc = (u32*)audio_decoder;
            ^
c:/Users/Dell/Desktop/lpp-3ds-master/source/luaSound.cpp:703:61: error: expected
 ')' at end of input
   audio_decoder->DecodeAsMono(wav_file->audiobuf, wav_file->audiobuf2
                                                             ^
c:/Users/Dell/Desktop/lpp-3ds-master/source/luaSound.cpp:703:61: error: expected
 '}' at end of input
c:/Users/Dell/Desktop/lpp-3ds-master/source/luaSound.cpp:703:61: error: expected
 '}' at end of input
make[1]: *** [luaSound.o] Error 1
make: *** [build] Error 2

**Comment by Rinnegatamante** [comment]
Your repository is corrupted for sure since you have for sure an outdated audio.h file at least.
