### ISSUE TITLE
How to use keyboard module 

### ISSUE THREAD

**Issue by Pirater12** [Rinnegatamante/lpp-3ds#35]
^^^can you give me an example

**Comment by Rinnegatamante** [comment]
I'll soon upload a new simple example for the Keyboard module.

At the moment you can take a look to CHMM2 code: https://github.com/Rinnegatamante/CHMM2/blob/great-refactor/source/main.lua#L389-L401

**Comment by Rinnegatamante** [comment]
Here's the official sample: https://github.com/Rinnegatamante/lpp-3ds/blob/master/samples/Miscellaneous/keyboard_and_console.lua
