### ISSUE TITLE
Switch to http request type by int gives bad default

### ISSUE THREAD

**Issue by ksanislo** [Rinnegatamante/lpp-3ds#38]
https://github.com/Rinnegatamante/lpp-3ds/commit/47af2ebfa253ab0b2406a41c14cc7fde20d5640e ends up giving a default request type of 0 which is invalid and always [comes back as an error](https://www.3dbrew.org/wiki/HTTPC:CreateContext) instead of a default GET (1)

**Comment by Rinnegatamante** [comment]
Fixed with this https://github.com/Rinnegatamante/lpp-3ds/commit/2382ee80bbb0f9a5f3de6bd4653ced433ddc16ae .
