### ISSUE TITLE
Security failure

### ISSUE THREAD

**Issue by yellows8** [Rinnegatamante/lpp-3ds#4]
* strcpy/strcat/sprintf should *never* be used directly with user-input.
* None of the gfx code does any range-checks for the input x/y parameters, hence arbitrary memory r/w relative to the used buffer.
* lpp-3ds uses lua integers for struct ptrs. Again, more arbitrary mem r/w. AFAICT this wouldn't be an issue if userdata was used instead: http://www.lua.org/pil/28.1.html

For PoCs for *some* of the affected functions see here: https://gist.github.com/yellows8/614a9c131ee2f3e4a78b

**Comment by Rinnegatamante** [comment]
lpp-3ds is not a C api so it will not provides any security check on its functions (they only slows interpreter which in itself already slows the execution of code when compared to a compiled source).
If a dev needs to do a security check for its works, it can just do this check using LUA code.
Anyway, in the future, i will work also on a more secure version with all needed security checks.

**Comment by yellows8** [comment]
"they only slows interpreter" Why exactly do you say that, have you actually tested that? Allowing scripts themselves to access arbitrary memory isn't the only problem, see here for example: https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaSound.cpp#L272
