### ISSUE TITLE
Network functions broken on .3dsx builds

### ISSUE THREAD

**Issue by Wolvan** [Rinnegatamante/lpp-3ds#40]
Attempting to use Network functions with the .3dsx build fails. It works on .cia and .3ds builds though.
A simple test I put together:
```
local WHITE = Color.new(255,255,255)
local pad = Controls.read()
local oldpad = pad
Screen.refresh()
Screen.clear(TOP_SCREEN)
Screen.clear(BOTTOM_SCREEN)
Screen.waitVblankStart()
Screen.flip()
Screen.debugPrint(5, 5, "Network: "..tostring(Network.isWifiEnabled()), WHITE, TOP_SCREEN)
while true do
	pad = Controls.read()
	if Controls.check(pad, KEY_A) and not Controls.check(oldpad, KEY_A) then
		System.exit()
	end
	oldpad = pad
end
```
This code is run in both .cia and .3dsx builds. The following results are achieved

| Build | Wifi ON | Wifi OFF |
| --- | --- | --- |
| .cia/.3ds | `Network: true` | `Network: false` |
| .3dsx | `Network: true` | `Network: true` |

`Network.downloadFile` and `Network.requestString` seem to be having similar problems.
Furthermore, I observed that Homebrew Launcher or Gridlauncher both show the Network as disabled after exiting the application.

I am using the lpp-3ds build 26b96a2

**Comment by Rinnegatamante** [comment]
Are you using the correct descriptor for networking features?

**Comment by Wolvan** [comment]
`Network.downloadFile(downloadURL, path, useragent, method, data)` is an example of what I am using

**Comment by Rinnegatamante** [comment]
Descriptor means XML file. In R5 packages there is a folder for that things.

**Comment by Wolvan** [comment]
I found the XML files in the r5 package, unfortunately I am not fully sure how to use them

**Comment by Rinnegatamante** [comment]
Rename the xml you need as the name of your homebrew and place it together with 3dsx file.

**Comment by Wolvan** [comment]
OK, Network.isWifiEnabled returns the right version with the XML, but downloadFile and requestString still do not seem to work.

I used the examples in the example folder of this repo. downloadFile does not seem to download the file and requestString returns the URL that you pass it. I tried using requestString("HelloWorld") and got `Hello World` back. I also tried `http://www.msftncsi.com/ncsi.txt` as url, but again, I got that as a result

**Comment by Rinnegatamante** [comment]
Have you tried the same code on CIA/3DS versions? Do they work fine?

**Comment by Wolvan** [comment]
Yeah, all my code works fine on the CIA/3DS version, it's only *hax builds that seem to be having trouble for some reason

**Comment by Rinnegatamante** [comment]
Try to replace in the descriptor soc:U with http:c

**Comment by Wolvan** [comment]
Same behavior as before, unfortunately

**Comment by ksanislo** [comment]
Does the 3dsx build still crash like the stack is all kinds of hosed up? That's the initial problem I had while doing the rewrite. Kinda felt like something deeper had gone wrong. I'm AFK out of cell service for a few more days, but I can help poke at it when I'm back.

**Comment by Wolvan** [comment]
Doesn't crash, no. As I said, Network.downloadFile just doesn't seem to download while Network.requestString returns the URL you pass it

**Comment by ksanislo** [comment]
So, the whole chunk of networking code is downright awful, with no proper return/bounds checking on pretty much anything. But I'm pretty sure that there's a memory corruption issue in at least that LPP build you're using. 

re: https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaNetwork.cpp#L260 causes crashing at https://github.com/Rinnegatamante/lpp-3ds/blob/master/source/luaNetwork.cpp#L267 on basic addition while adding 20345 + 4096, which had been  reproducible with a few builds with a simple test Lua script. This same code runs perfectly fine when it's not part of Lua, so I'd guess something elsewhere in the interpreter was actually corrupting memory on the stack.

At the very least, I'd recommend trying again with the latest commit of lua and see if things are still acting strangely. The http under 3dsx however might be an entirely unrelated broken situation, as I've no idea how the hax is initializing http:c for homebrew at all, but there have been on and off reports of it being broken in general in the past and nobody caring enough to fix it. That's why I've always stuck with the 100% cia build environment for my own development and personally consider the "homebrew" sandbox to be only good enough for getting a CFW installed.

**Comment by Wolvan** [comment]
I tried using the latest nightly 74f39aa85908697abc2560002733e9230f76a014
requestString now returned the data that I sent with the post request

**Comment by Rinnegatamante** [comment]
You inteded to say "I requested" or have you received the URL again?
What about downloadFile?

**Comment by Wolvan** [comment]
`local remoteData = Network.requestString(url, useragent, method, jsondata)`
Yeah that is probably what I meant. Haven't tried downloadFile, give me a second

**Comment by Wolvan** [comment]
Downloaded does not seem to download the file at all.

**Comment by ksanislo** [comment]
@Wolvan what firmware are you on btw?

**Comment by Wolvan** [comment]
11.0 Sysnand CFW

**Comment by ksanislo** [comment]
Can you flash back to 10.x from a backup and see if things are the same way pre-11?

**Comment by ksanislo** [comment]
Or boot an 9.2 emunand if you have one. I just deleted mine off my last system yesterday to stop the accidental booting 9.2 in my pocket. :(

**Comment by Wolvan** [comment]
I don't have a 10.7 backup around anymore, unfortunately. Is there a ctrtransfer nand available?

**Comment by Wolvan** [comment]
Download does not occur on 9.2 either

**Comment by ksanislo** [comment]
@Wolvan Can you upload a copy of the lpp-3ds.3dsx and the script that you're using to test right now? I'd like make sure I'm duplicating your test environment.. Also, how are you loading up HBL in your system?

**Comment by ksanislo** [comment]
FWIW, I ask because the 4PM hourly and the network string example seem to work just fine for me, but i'm booting up with hbl_launcher_loader 1.2 as a .cia, not using a game *hax...

**Comment by Rinnegatamante** [comment]
I know this could sound like "i don't want to fix it, just take this workaround" but since http:C seems to be a lot more unreliable than soc:U, why not using sockets to realize a downloader?

In lpp-vita there's also a little sample (that can be improved with chunks saving on storage and a progress bar since it's an asynchronous download) you can easily adapt to lpp-3ds (literally you only have to change rendering stuffs since sockets have same syntax): https://github.com/Rinnegatamante/lpp-vita/blob/master/samples/File%20Downloader/index.lua

**Comment by Wolvan** [comment]
Nah, I'll definitely give it a try and see if I can't make it work

**Comment by ksanislo** [comment]
Keep in mind that if you use sockets instead, you're going to have to re-implement quite of bit of how HTTP works yourself. There's a lot of the more advanced stuff that is handled automatically by http:C like chunked encoding and keep-alive and the like. It's definitely doable, but you'll need this: http://www.rfc-base.org/txt/rfc-2616.txt

**Comment by Wolvan** [comment]
Oh this sounds just lovely. You said with the latest build it works for you? What exactly is the test code you use?

**Comment by ksanislo** [comment]
I grabbed the lpp 3dsx from nightlies, renamed it as lpp-test.3dsx, the example https://github.com/Rinnegatamante/lpp-3ds/blob/master/samples/Network/net_request_string.lua renamed as index.lua, and dropped them both into /3ds/lpp-test/ and then loaded hbll1.2 (with *hax 2.7, I believe it reported as it booted.)

What are you testing with?

**Comment by Wolvan** [comment]
[LPP.zip](https://github.com/Rinnegatamante/lpp-3ds/files/442958/LPP.zip)
That's the files I use in SDMC:/3ds/Homebr3w. Build is https://github.com/Rinnegatamante/lpp-3ds/commit/74f39aa85908697abc2560002733e9230f76a014

Expected result: Write `Last version: FIX` to the screen
Result: Writes `Last version: http://rinnegatamante.netsons.org/ORGANIZ3D.txt` to the screen, overflowing the screen and part of the string ending up on the bottom screen

**Comment by ksanislo** [comment]
I don't have an SD reader handy, so I may not be able to test this until after work. I'll see what I can come up with. However, something that you can try yourself would be to double check the ROP otherapp payload that you're using with hbll...maybe you have an old/broken otherapp payload version that is being used somehow? Also, it might be worth testing via oothax or real ninjhax or something as well.

**Comment by Wolvan** [comment]
No look on an updated hbll payload nor a freshly installed ninjhax payload

**Comment by ksanislo** [comment]
What region/model is your 3DS? I was testing on a USA 2DS last night.

**Comment by Wolvan** [comment]
See https://github.com/Rinnegatamante/lpp-3ds/issues/40#issuecomment-242995087
O3DS XL, 11.0E no region change on sysnand cfw

**Comment by ksanislo** [comment]
Deferring to the temp for testing... I'm 99.9% sure this is the exact same script and lua commit revision that I tested with last night that was working.

**Comment by ksanislo** [comment]
https://gbatemp.net/threads/need-to-test-a-simple-lua-script-3dsx-can-anyone-help.439713/

**Comment by ksanislo** [comment]
@Wolvan  You've already tried, this... right?

https://gbatemp.net/threads/need-to-test-a-simple-lua-script-3dsx-can-anyone-help.439713/page-2#post-6639533

**Comment by Wolvan** [comment]
Alright, I used checkService. soc:U access I do get but http:C access, even when using the descriptor, I do never get. checkService always returns false

**Comment by Rinnegatamante** [comment]
try to set http:c instead of http:C

**Comment by Wolvan** [comment]
Actually tried that already

**Comment by ksanislo** [comment]
@Rinnegatamante  Where does that .xml file get loaded to build the service list at? I'm not seeing code for that anywhere in HBL... do you know?

**Comment by ksanislo** [comment]
@Wolvan in theory, you /might/ just need to own/install an app or game that has access to all of the services that the lua 3dsx requires, and then it will "just work"...  I don't have any good suggestions of what that would be though.

**Comment by Wolvan** [comment]
So basically just stick to the .cia version

**Comment by ksanislo** [comment]
Yeah. This problem seems to be much deeper than just Homebr3w, I'd just avoid it entirely if possible.

**Comment by Rinnegatamante** [comment]
@ksanislo https://github.com/smealum/3ds_hb_menu/blob/master/source/descriptor.cpp#L23-L105

**Comment by ksanislo** [comment]
Yeah, I found that eventually. Wasn't expecting a cpp in my search so I'd missed it.

**Comment by ksanislo** [comment]
fwiw, the way I read that is that if the xml doesn't exist then it will scan the file for service names and attempt to find them to use anyway.

**Comment by Rinnegatamante** [comment]
Yes but lpp-3ds uses too much services and if you don't have a descriptor it will end up to prevent you to be able to use http:c, csnd:SND, cam:u, ptm:u randomly depending on what target it will select (that's why i put a couple of descriptors in R5 package of lpp-3ds).

**Comment by ksanislo** [comment]
@Wolvan Have you tried using the xml to launch the 3dsx with a specific titleid instead of using the auto-scan? Something like is recommended [for the MVD service](https://github.com/devkitPro/3ds-examples/blob/master/mvd/mvd.xml)

Unfortunately, I don't have recommendations for which title to try with this, as I'm not sure how to determine what services each one can provide yet...

**Comment by Rinnegatamante** [comment]
Youtube should be good enough.

**Comment by ksanislo** [comment]
YouTube should be 00040000000CCD00 or 00040000000B0F00 depending on if you're using the EU or US version...  If it works, you'll need to make sure to tell people they need to install it from the eshop in your release notes somewhere, I don't think I've got it installed on any of my consoles.

**Comment by Wolvan** [comment]
It actually works, taking over Youtube works perfectly! What about the other regions though, btw? Does Japan even have the Youtube app for example? Or is there maybe a system app one can take over to get access to http:C? Would the webbrowser applet work here? Also, the descriptor seems to be needed as HBL does not seem to be able to understand that Youtube offers http:C. Just having the Descriptor ask for http:C doesn't work either, what could be the reason for that?

**Comment by ksanislo** [comment]
I don't think it's that ninjhax doesn't realize that YT has the privs for http:C, I suspect that it's choosing to not take over it in favor of a different app that has another service that it thinks is more important/useful, despite the manual service declaration in the .xml.

FWIW, This isn't just Lua having this problem lately, I've seen a few very basic (nearly 100% stock example source) apps that fail to get http:C when run as 3dsx as well. There might have been some kind of a change that has started causing it, or it might be that it's been broken forever and this is the "unreliable http support" people have always bitched about.

**Comment by Wolvan** [comment]
Is there a pre-installed app that I could take over? I tried taking over Spider but for some reason it tells me the app is not installed

**Comment by ksanislo** [comment]
Are you possibly using an n3DS model? Spider is old 3DS only, while Skater is the new 3DS replacement. 

Also, keep in mind that some people end up with a dummy browser depending on how they've upgraded, and that might be even harder for someone to fix without a CFW than just installing YouTube.

**Comment by Wolvan** [comment]
No I am on o3ds. I did add Skater's TIDs as well though, so that shouldn't have been the problem. But I see what you mean. Any other idea?

**Comment by ksanislo** [comment]
Not really sure what to do about it... Can you verify the tid via FBI or something to be sure you've got the right one? I think you're definitely right with trying to find a system service that can work though, and barring that, I'd look if there's something that can be installed via legit CIA for people under fw11 who don't have access to the eshop.

Realistically though, this app downloads cia files, so I'd expect that anyone interested in it has a CFW and can install whatever might be required to make it work.

**Comment by Wolvan** [comment]
I am going to see about implementing 3dsx dl support is the problem I am having here. But I see what you mean, and yeah, I did check FBI. It just doesn't seem to want to detect the browser being installed

**Comment by ksanislo** [comment]
@Wolvan , Kartik over on the temp reports that Face Raiders has http:C, as well as cam services, and has shipped pre-loaded on all 3DS systems for all regions, as far as I can tell.

**Comment by Wolvan** [comment]
You got the TIDs for Face Riaders? Also, mind linking me to the post?

**Comment by Wolvan** [comment]
Taking over Face raiders actually works perfectly!

**Comment by Rinnegatamante** [comment]
That's a nice discovery, it's near to be perfect for lpp-3ds

**Comment by Wolvan** [comment]
3dsx homebrew that requires internet access in general I'd say

**Comment by ihaveamac** [comment]
in that case, here's an XML for each Face Raiders title in each region:
```xml
<targets selectable="false">
	<!-- Face Raiders JPN/USA/EUR/KOR -->
	<title mediatype="0">0004001000020D00</title>
	<title mediatype="0">0004001000021D00</title>
	<title mediatype="0">0004001000022D00</title>
	<title mediatype="0">0004001000027D00</title>
	<!-- New3DS Face Raiders JPN/USA/EUR/KOR -->
	<title mediatype="0">0004001020020D00</title>
	<title mediatype="0">0004001020021D00</title>
	<title mediatype="0">0004001020022D00</title>
	<title mediatype="0">0004001020027D00</title>
</targets>
```

**Comment by Wolvan** [comment]
@ihaveamac You are missing `0004001000026D00` and `0004001000028D00` for CHN and TWN o3ds respectively

**Comment by ihaveamac** [comment]
those regions don't have *hax so I intentionally left them out.

**Comment by Wolvan** [comment]
ah, fair enough then

**Comment by ksanislo** [comment]
@Wolvan Sorry, been busy with work today... The original mention that it had http:c was [here](https://gbatemp.net/threads/release-multidownload-all-type-file-downloader-for-3ds.437631/page-4#post-6664948)

It sounds like you guys have this all sorted out now, nice!

**Comment by Substance12** [comment]
I know this issue is closed but THANK YOU SO MUCH FOR THE INFO HERE HOLY SHIT. I was using cam:u functions and it always broke networking, but using the Face Raiders descriptor fixed everything!
