### ISSUE TITLE
3rdparty may too old.

### ISSUE THREAD

**Issue by qqwwee421** [Rinnegatamante/lpp-3ds#45]
3DS applications now need to be built with -mfloat-abi=hard in devkitARM,but all the lib is built with softfp(i guess).

**Comment by Rinnegatamante** [comment]
No need to be built with hardware floating point. vorbisfile doesn't work with hardware fpoint.

**Comment by qqwwee421** [comment]
But it will made a error:cannot find 3dsx_crt0.o. What should i do?

**Comment by Rinnegatamante** [comment]
You must go to /devkitPro/devkitARM/arm-none-eabi/lib and you should execute a "make CRT=3dsx".

**Comment by qqwwee421** [comment]
Thank you. :)
