### ISSUE TITLE
Dofile from/Access to RomFS

### ISSUE THREAD

**Issue by Wolvan** [Rinnegatamante/lpp-3ds#49]
Sorry if this is a stupid question, but is it possible to access resources from the RomFS from a lpp3ds script?

**Comment by Rinnegatamante** [comment]
Yes, dofile("romfs:/index.lua") for example.

Same for other functions (loadImage and similars).

CHMM2 for example uses romfs partition: https://github.com/Rinnegatamante/CHMM2/blob/master/source/index.lua#L3-L16

**Comment by Wolvan** [comment]
Ah, that's easy enough! Thanks a lot, Rin
