### ISSUE TITLE
Tutorial for making homebrew using this library?

### ISSUE THREAD

**Issue by MineRobber9000** [Rinnegatamante/lpp-3ds#51]
I can't find a tutorial, and I really want to make a game using this library. I would have asked on the forums, but I can't find the button to make a new thread.

**Comment by Wolvan** [comment]
Maybe look at some of the many listed apps that have been made with lpp?
https://github.com/Rinnegatamante/lpp-3ds#showcase

**Comment by MineRobber9000** [comment]
I know how you write the code, but how do you turn it into a .3dsx?

**Comment by Wolvan** [comment]
You don't turn lpp into a .3dsx file. You take the lpp binary (the 3dsx file in the release archive) and drop the index.lua that you write in the same folder. Done.

(If you want, take a look at Homebr3w's makefile to see what I do to automatically turn the source into a release ready zip/tar archive)

**Comment by Rinnegatamante** [comment]
You can do as @Wolvan suggested or you can use lpp-builder to include your source files in romfs partition.
