### ISSUE TITLE
System.exit() causes loop instead of returning to homebrew menu

### ISSUE THREAD

**Issue by thatguywiththatname** [Rinnegatamante/lpp-3ds#52]
## System details:

 - EU N3DS
 - 11.2 
 - Soundhax entrypoint
 - Latest version of lpp-3ds

## Problem

Calling System.exit() causes the bottom screen to alternate between red and black, constantly happens until I force close it using L+R+Down+B (doing this sometimes causes a complete crash, meaning I have to reboot the whole system)

**Comment by Rinnegatamante** [comment]
Hardly doubt the issue is in lpp-3ds since it never had such issues before on both CIA and 3DSX versions. Are you sure you cleared every resource before calling Systemexit? (3DS doesn't perform an automatic garbage collection when exiting).

**Comment by thatguywiththatname** [comment]
Ok, maybe its just my ds?


What do you mean by by "cleared every resource"? Is there anything particular, because even just writing code that closes itself after opening it causes it to happen.
