### ISSUE TITLE
[O3DS] Strange error with romfs

### ISSUE THREAD

**Issue by bcnjr5** [Rinnegatamante/lpp-3ds#56]
When I run the attached CIA, `loadfile` fails with the error `Function not implemented` when called with a `romfs:/` name.

Am I doing something wrong?

 - An example of the failing call is `loadfile('romfs:/p3600/init.lua')()`. (The target file _does_ exist.)
 - `System.doesFileExist` returns `false` as well. (Once again, the file _is_ there...)

[case.zip](https://github.com/Rinnegatamante/lpp-3ds/files/980595/case.zip) (contains CIA and the contents of the romfs)

**Comment by Rinnegatamante** [comment]
What have you used to build the CIA file? Just to be sure it's not a CIA issue. Btw loadfile has not been patched like dofile so this is probably why it fails with romfs:/

**Comment by bcnjr5** [comment]
I am using the "Safe" ELF file from lpp-3ds r5, and [this RSF file](https://gist.github.com/bcnjr5/46e56989ee39992d43f04c05642bf798).

The Makefile looks like this: (simplified)

```make
# Main target
p3600.cia:

BANNERTOOL ?= bannertool
MAKEROM ?= makerom
tDSTOOL ?= 3dstool


files := cia_romfs/index.lua cia_romfs/p3600/init.lua # etc...

icon.smdh: rsrc/icon.png
	$(BANNERTOOL) makesmdh -o icon.smdh \
	  -i rsrc/icon.png \
	  -s 'p3600' \
	  -l 'p3600 -- A game.' \
	  -p 'bcnjr5 & GitHub contributors' \
	  -r regionfree

banner.bnr: rsrc/banner.png rsrc/banner.ogg
	$(BANNERTOOL) makebanner -o $(engine)_banner.bnr \
	  -i rsrc/$(engine)/banner.png \
	  -a rsrc/$(engine)/banner.ogg

cia_romfs.bin: $(files)
	$(tDSTOOL) -cvtf romfs cia_romfs.bin --romfs-dir cia_romfs

p3600.cia: cia_romfs.bin icon.smdh banner.bnr rsrc/lpp-3ds.elf rsrc/cia.rsf
	$(MAKEROM) \
	  -f cia \
	  -o p3600.cia \
	  -ver 0 \
	  -elf rsrc/lpp-3ds.elf \
	  -rsf rsrc/cia.rsf \
	  -icon icon.smdh \
	  -banner banner.bnr \
	  -exefslogo \
	  -target t \
	  -romfs cia_romfs.bin
```

**Comment by bcnjr5** [comment]
After changing `romfs:/index.lua` a little bit, it seems that `dofile` doesn't work either. I'll dump the romfs and see if the files are still there... :confused:

**Comment by bcnjr5** [comment]
The romfs is all correct, and the files are in place.

**Comment by Rinnegatamante** [comment]
Btw, i suggest you to use the nightly instead of R5: http://rinnegatamante.it/lpp-nightly.php

Let me know if this happens with nightly too.

**Comment by bcnjr5** [comment]
It seems to work just fine, thanks!
