### ISSUE TITLE
Build error.

### ISSUE THREAD

**Issue by mariohackandglitch** [Rinnegatamante/lpp-3ds#6]
Trying to build lastest commit throws this error: c:/lpp-3ds-master/source/include/lua/lstate.h:144:21: error: 'STRCACHE_SIZE' undeclared here (not in a function)
   TString *strcache[STRCACHE_SIZE][1];  /* cache for strings in API */

**Comment by Rinnegatamante** [comment]
Solved with this commit: https://github.com/Rinnegatamante/lpp-3ds/commit/9271cb1e094ebbf6aff0a7377fff8c52c4279eac
