### ISSUE TITLE
Index.lua file not found

### ISSUE THREAD

**Issue by JohnB17** [Rinnegatamante/lpp-3ds#60]
When I try running this, I get the error of "index.lua file not found"
![image](https://user-images.githubusercontent.com/63297273/88336459-04f54400-cd03-11ea-8d7b-9732b9ade127.jpg)

**Comment by lorenzholzbauer** [comment]
Because you haven't created an index.lua file yet.

**Comment by JohnB17** [comment]
How do I create it? Do I just make a file called "index.lua" ? Or do I have to put something in it?

**Comment by JohnB17** [comment]
Oh. It is an interpreter. I thought it was a media player.
