### ISSUE TITLE
System.checkBuild() causes not enough memory.

### ISSUE THREAD

**Issue by mariohackandglitch** [Rinnegatamante/lpp-3ds#7]
Calling System.checkBuild() causes not enough memory.

**Comment by Rinnegatamante** [comment]
I used it in different homebrews (first i remember are Sunshell and CHMM). Are you sure error is cause by this line of code? It shouldn't allocate any memory block.

**Comment by mariohackandglitch** [comment]
I think it is the problem, I'll check again since I removed it from the code.

**Comment by mariohackandglitch** [comment]
I didn't know what happened, but now it works.
