### ISSUE TITLE
Wav player not working properly.

### ISSUE THREAD

**Issue by mariohackandglitch** [Rinnegatamante/lpp-3ds#8]
Using wav player as cia build corrupts the sound system, also after lpp is closed. (Using rxtools).
This happens on most recent commit, but not the previous.

**Comment by Rinnegatamante** [comment]
Can you upload somewhere your WAV file to inspect the issue?

**Comment by mariohackandglitch** [comment]
Here it is:
http://www.mediafire.com/listen/psk2did4frosnr6/music0.wav
It causes a beep with no streaming, and a 5 second loop with streaming.

**Comment by Rinnegatamante** [comment]
New csnd wrapper completely broke luaSound with no reason cause systemcalls are the same.

**Comment by Rinnegatamante** [comment]
It should be fixxed with latest commits.
